---

- name: Ensure admin group is present
  group:
    name: admin
    state: present
  become: yes

- name: ansible user shell
  user:
    name: "{{ ansible_user }}"
    shell: /bin/zsh
  become: yes

- name: Check if pubkey file exists
  local_action: stat path="~/.ssh/id_rsa.pub"
  register: file

- name: Set authorized key took from file
  authorized_key:
    user: "{{ ansible_user }}"
    state: present
    key: "{{ lookup('file', '~/.ssh/id_rsa.pub') }}"
  when: file.stat.exists

- name: No passwd for admin group on sudo
  lineinfile:
    path: /etc/sudoers
    state: present
    regexp: '^%ADMIN ALL='
    line: '%ADMIN ALL=(ALL) NOPASSWD: ALL'
    validate: '/usr/sbin/visudo -cf %s'
  become: yes

- name: Check if private key file exists
  local_action: stat path="~/.ssh/id_rsa"
  register: file

- name: Copy local private key file to remote if exists
  copy:
    src: ~/.ssh/id_rsa
    dest: ~/.ssh/id_rsa
    mode: 0600
  when: file.stat.exists

- name: Copy local public key file to remote if exists
  copy:
    src: ~/.ssh/id_rsa.pub
    dest: ~/.ssh/id_rsa.pub
    mode: 0644
  when: file.stat.exists
